#script con instrucciones para la carga de datos

LOAD DATA
LOCAL INFILE '/home/yelstin/Escritorio/USAC_REPOSITORIOS/MIA_2S2020_PRACTICA1/MIA_API1S21/GRAND_VIRUS_EPICENTER.csv'
INTO TABLE TEMPORAL
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(NOMBRE_VICTIMA,APELLIDO_VICTIMA,DIRECCION_VICTIMA,FECHA_PRIMERA_SOSPECHA,
FECHA_CONFIRMACION,FECHA_MUERTE,ESTADO_VICTIMA,NOMBRE_ASOCIADO,APELLIDO_ASOCIADO,
FECHA_CONOCIO,CONTACTO_FISICO,FECHA_INICIO_CONTACTO,FECHA_FIN_CONTACTO,
NOMBRE_HOSPITAL,DIRECCION_HOSPITAL,UBICACION_VICTIMA,FECHA_LLEGADA,FECHA_RETIRO,
TRATAMIENTO,EFECTIVIDAD,FECHA_INICIO_TRATAMIENTO,FECHA_FIN_TRATAMIENTO,
EFECTIVIDAD_EN_VICTIMA
);
/*V2 LOADATA*/
LOAD DATA
LOCAL INFILE '/home/yelstin/Escritorio/USAC_REPOSITORIOS/MIA_2S2020_PRACTICA1/MIA_API1S21/GRAND_VIRUS_EPICENTER.csv'
INTO TABLE TEMPORAL
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(NOMBRE_VICTIMA,APELLIDO_VICTIMA,DIRECCION_VICTIMA,@var1,
@var2,@var3,ESTADO_VICTIMA,NOMBRE_ASOCIADO,APELLIDO_ASOCIADO,
@var4,CONTACTO_FISICO,@var5,@var6,
NOMBRE_HOSPITAL,DIRECCION_HOSPITAL,UBICACION_VICTIMA,@var7,@var8,
TRATAMIENTO,EFECTIVIDAD,@var9,@var10,
EFECTIVIDAD_EN_VICTIMA
)
set FECHA_PRIMERA_SOSPECHA = STR_TO_DATE (@var1, '%d/%m/%Y %H:%i:%s');
set FECHA_CONFIRMACION = STR_TO_DATE (@var2, '%d/%m/%Y %H:%i:%s');
set FECHA_MUERTE = STR_TO_DATE (@var3, '%d/%m/%Y %H:%i:%s');
set FECHA_CONOCIO = STR_TO_DATE (@var4, '%d/%m/%Y %H:%i:%s');
set FECHA_INICIO_CONTACTO = STR_TO_DATE (@var5, '%d/%m/%Y %H:%i:%s');
set FECHA_FIN_CONTACTO = STR_TO_DATE (@var6, '%d/%m/%Y %H:%i:%s');
set FECHA_LLEGADA = STR_TO_DATE (@var7, '%d/%m/%Y %H:%i:%s');
set FECHA_RETIRO = STR_TO_DATE (@var8, '%d/%m/%Y %H:%i:%s');
set FECHA_INICIO_TRATAMIENTO = STR_TO_DATE (@var9, '%d/%m/%Y %H:%i:%s');
set FECHA_FIN_TRATAMIENTO  = STR_TO_DATE (@var10, '%d/%m/%Y %H:%i:%s');

/*DEFINICION DE DATOS TABLA HOSPITAL*/
INSERT INTO HOSPITAL (hospital) (
    SELECT DISTINCT NOMBRE_HOSPITAL FROM TEMPORAL WHERE NOMBRE_HOSPITAL NOT LIKE ''
    );

/*DEFINICION DE DATOS EN TABLA TRATAMIENTO*/
INSERT INTO TRATAMIENTO (tratamiento,efectividad) (
    SELECT DISTINCT TRATAMIENTO, EFECTIVIDAD FROM TEMPORAL WHERE TRATAMIENTO NOT LIKE '' 
);

/*DEFINICION DE DATOS EN TABLA CONTACTO*/
INSERT INTO TIPO_CONTACTO(contacto) (
    SELECT DISTINCT CONTACTO_FISICO FROM TEMPORAL WHERE CONTACTO_FISICO NOT LIKE ''
);

/*DEFINICION DE DATOS EN ESTADO VICTIMA*/
INSERT INTO ESTADO_VICTIMA (estado) (
    SELECT DISTINCT ESTADO_VICTIMA FROM TEMPORAL WHERE ESTADO_VICTIMA NOT LIKE ''
);

/*DEFINICION DE VICTIAM*/
INSERT INTO VICTIMA (nombre_v,apellido_v,cod_estado) (

);
